Add typed Parquet support
spotify/scio pull request #3591
Opened 2021-02-05 21:37 UTC by nevillelyh

2021-02-08 20:27 UTC, ClaireMcGinty approved these changes

2021-02-08 20:29 UTC, ClaireMcGinty requested changes

2021-02-08 20:29 UTC, ClaireMcGinty commented on scio-parquet/src/main/java/com/spotify/scio/parquet/types/ParquetTypeSink.java
> + * Copyright 2017 Spotify AB.
```suggestion
 * Copyright 2021 Spotify AB.
```

2021-02-08 20:29 UTC, ClaireMcGinty commented on scio-parquet/src/main/java/com/spotify/scio/parquet/WriterUtils.java
> + * Copyright 2017 Spotify AB.
```suggestion
 * Copyright 2021 Spotify AB.
```

2021-02-08 20:29 UTC, ClaireMcGinty commented on scio-parquet/src/main/scala/com/spotify/scio/parquet/types/ParquetTypeIO.scala
> + * Copyright 2020 Spotify AB.
```suggestion
 * Copyright 2021 Spotify AB.
```

2021-02-08 20:29 UTC, ClaireMcGinty commented on scio-parquet/src/main/scala/com/spotify/scio/parquet/types/package.scala
> + * Copyright 2020 Spotify AB.
```suggestion
 * Copyright 2021 Spotify AB.
```

2021-02-08 20:29 UTC, ClaireMcGinty commented on scio-parquet/src/test/scala/com/spotify/scio/parquet/types/ParquetTypeIOTest.scala
> + * Copyright 2020 Spotify AB.
```suggestion
 * Copyright 2021 Spotify AB.
```

2021-02-09 09:34 UTC, regadas reviewed
Overall looks great! just left a small comment to make it consistent.

2021-02-09 09:34 UTC, regadas commented on scio-parquet/src/main/scala/com/spotify/scio/parquet/types/package.scala
> +package object types {
wdyt of moving this to a `syntax` package definition? it would follow the rest of the packages.

2021-02-09 19:54 UTC, merged

2021-02-10 11:30 UTC, regadas commented on scio-parquet/src/main/scala/com/spotify/scio/parquet/types/package.scala
> +package object types {
Ahh I missed that, makes sense, and I see #3598. 👍