move scalacheck Pipeline utils to separate trait
spotify/scio pull request #4208
Opened 2022-01-14 21:24 UTC by clairemcginty

scalacheck wasn't being exported as a compile dep of `scio-test` and causing issues with the `PipelineTestUtils` trait. this separates the traits & de-scopes scalacheck dependency.

2022-01-14 21:25 UTC, kellen approved these changes
👍

2022-01-14 21:27 UTC, stormy-ua approved these changes
👍

2022-01-18 12:25 UTC, regadas requested changes
I just realized that this was added to `scio-test` and looking at this I don't think it should be added to this module; Since this is not really enhancing scio testing by itself ,only nice helpers to work with scalacheck, these should be added to `scio-extra`.

Since this is broken in 0.11.3 we should take the opportunity to move them. This also avoids pulling scalacheck in scio-test unnecessarily.

2022-01-18 17:22 UTC, regadas approved these changes

2022-01-18 17:33 UTC, merged